
import java.text.DecimalFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Jesus
 */
public class UsoProducto extends javax.swing.JFrame {
    ProductoFresco fresco = new ProductoFresco();
    ProductosRefrigerados refrigerados = new ProductosRefrigerados();
    ProductosCongelados congelados = new ProductosCongelados();
     DecimalFormat decimal = new DecimalFormat("#.##");
    DefaultTableModel modelo;
    Object registro[]=new Object[8];
    /**
     * Creates new form UsoProducto
     */
    public UsoProducto() {
        initComponents();
        modelo=(DefaultTableModel)tabla.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        cerrar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        fechaenv = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        paisorg = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        codigo = new javax.swing.JTextPane();
        registrar2 = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        temperatura = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        registrar3 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        preciou = new javax.swing.JTextField();
        cantstop = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        fechacad = new javax.swing.JTextField();
        numlote = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        limpiar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 204, 204));
        jLabel1.setFont(new java.awt.Font("Bahnschrift", 1, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 255, 204));
        jLabel1.setText("PRODUCTOS AGRICOLAS S.A");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 450, 60));

        cerrar.setBackground(new java.awt.Color(153, 0, 0));
        cerrar.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        cerrar.setText("Cerrar");
        cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarActionPerformed(evt);
            }
        });
        getContentPane().add(cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 30, 160, 30));

        jLabel6.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 204));
        jLabel6.setText("PRODUCTOS FRESCOS");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 220, 40));

        jLabel8.setFont(new java.awt.Font("Bahnschrift", 1, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 0));
        jLabel8.setText("PRODUCTOS CONGELADOS");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 220, 250, 30));

        fechaenv.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        fechaenv.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fechaenv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fechaenvActionPerformed(evt);
            }
        });
        getContentPane().add(fechaenv, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, 160, 30));

        jLabel9.setFont(new java.awt.Font("Bahnschrift", 1, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 204));
        jLabel9.setText("Fecha de envasado:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, -1, -1));

        jLabel10.setFont(new java.awt.Font("Bahnschrift", 1, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 153));
        jLabel10.setText("Pais de origen:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 180, 30));

        paisorg.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        paisorg.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(paisorg, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 320, 160, 30));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 900, 10));

        jScrollPane1.setViewportView(codigo);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 420, 160, 30));

        registrar2.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        registrar2.setForeground(new java.awt.Color(0, 51, 255));
        registrar2.setText("Registrar");
        registrar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrar2ActionPerformed(evt);
            }
        });
        getContentPane().add(registrar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 420, 160, 30));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 900, 10));

        jLabel12.setFont(new java.awt.Font("Bahnschrift", 1, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 204, 0));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Temperatura de congelacion: ");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 530, 260, 30));

        temperatura.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        temperatura.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(temperatura, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 530, 160, 30));
        getContentPane().add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, 900, 10));

        registrar3.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        registrar3.setForeground(new java.awt.Color(0, 51, 255));
        registrar3.setText("Registrar");
        registrar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrar3ActionPerformed(evt);
            }
        });
        getContentPane().add(registrar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 530, 160, 30));

        jLabel13.setFont(new java.awt.Font("Bahnschrift", 1, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 204, 0));
        jLabel13.setText("Informacion del producto");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 580, 240, 30));
        getContentPane().add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 580, 900, 10));

        jPanel2.setBackground(new java.awt.Color(0, 204, 153));
        jPanel2.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Bahnschrift", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 0, 0));
        jLabel4.setText("Cantidad en stop: ");
        jLabel4.setToolTipText("");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(370, 10, 170, 30);

        jLabel5.setFont(new java.awt.Font("Bahnschrift", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 0, 0));
        jLabel5.setText("Precio por unidad: ");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(360, 60, 170, 30);

        preciou.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        preciou.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        preciou.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                preciouActionPerformed(evt);
            }
        });
        jPanel2.add(preciou);
        preciou.setBounds(530, 60, 160, 30);

        cantstop.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        cantstop.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cantstop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantstopActionPerformed(evt);
            }
        });
        jPanel2.add(cantstop);
        cantstop.setBounds(530, 20, 160, 30);

        jLabel2.setFont(new java.awt.Font("Bahnschrift", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 0));
        jLabel2.setText("Fecha de caducidad:");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(10, 10, 190, 30);

        jLabel3.setFont(new java.awt.Font("Bahnschrift", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 0, 0));
        jLabel3.setText("Numero de lote:");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(10, 50, 180, 30);

        fechacad.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        fechacad.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fechacad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fechacadActionPerformed(evt);
            }
        });
        jPanel2.add(fechacad);
        fechacad.setBounds(190, 10, 160, 30);

        numlote.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        numlote.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(numlote);
        numlote.setBounds(190, 60, 160, 30);

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 910, 100));

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Fecha de Cadu.", "Num. Lote", "Cant. stop", "Precio x U", "Fecha Ven.", "Pais Origen", "Cod. Supervicion", "Temperatura"
            }
        ));
        jScrollPane4.setViewportView(tabla);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 610, 830, 120));

        jPanel3.setBackground(new java.awt.Color(0, 153, 204));
        jPanel3.setLayout(null);

        jLabel11.setFont(new java.awt.Font("Bahnschrift", 1, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 0, 255));
        jLabel11.setText("Codigo del organismo de supervision alimentaria: ");
        jLabel11.setToolTipText("");
        jPanel3.add(jLabel11);
        jLabel11.setBounds(10, 50, 470, 30);

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 910, 100));

        limpiar.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        limpiar.setForeground(new java.awt.Color(0, 0, 255));
        limpiar.setText("LIMPIAR");
        limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarActionPerformed(evt);
            }
        });
        getContentPane().add(limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 520, 140, 40));

        jPanel4.setBackground(new java.awt.Color(255, 51, 51));
        jPanel4.setLayout(null);
        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, 910, 110));

        jPanel5.setBackground(new java.awt.Color(255, 153, 153));
        jPanel5.setLayout(null);
        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 580, 910, 160));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondotitulo.png"))); // NOI18N
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 880, 90));

        jLabel7.setFont(new java.awt.Font("Bahnschrift", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 204));
        jLabel7.setText("PRODUCTOS REFRIGERADOS");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 220, -1, 30));

        jRadioButton1.setText("Productos Fresco");
        getContentPane().add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 220, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fechacadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fechacadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fechacadActionPerformed

    private void preciouActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_preciouActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_preciouActionPerformed

    private void fechaenvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fechaenvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fechaenvActionPerformed

    private void cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarActionPerformed
        // TODO add your handling code here:
         System.exit(0);
    }//GEN-LAST:event_cerrarActionPerformed

    private void registrar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrar2ActionPerformed
        // TODO add your handling code here:
        refrigerados = new ProductosRefrigerados(fechacad.getText(),Integer.parseInt(numlote.getText()),Integer.parseInt(cantstop.getText()),Double.parseDouble(preciou.getText()),codigo.getText());
        
        registro[0]=fechacad.getText();
        registro[1]=numlote.getText();
        registro[2]=cantstop.getText();
        registro[3]=preciou.getText();
        registro[6]=codigo.getText();
         JOptionPane.showMessageDialog(rootPane,"Producto Registrado");
        modelo.addRow(registro);
        
    }//GEN-LAST:event_registrar2ActionPerformed

    private void registrar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrar3ActionPerformed
        // TODO add your handling code here:
        congelados = new ProductosCongelados(fechacad.getText(),Integer.parseInt(numlote.getText()),Integer.parseInt(cantstop.getText()),Double.parseDouble(preciou.getText()),temperatura.getText());
        
        
        registro[0]=fechacad.getText();
        registro[1]=numlote.getText();
        registro[2]=cantstop.getText();
        registro[3]=preciou.getText();
        registro[7]=temperatura.getText();
         JOptionPane.showMessageDialog(rootPane,"Producto Registrado");
        modelo.addRow(registro);
    }//GEN-LAST:event_registrar3ActionPerformed

    private void cantstopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantstopActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cantstopActionPerformed

    private void limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarActionPerformed
        // TODO add your handling code here:
        fechacad.setText("");
        numlote.setText("");
        cantstop.setText("");
        preciou.setText("");
       temperatura.setText("");
        fechaenv.setText("");
        paisorg.setText("");
        codigo.setText("");
    }//GEN-LAST:event_limpiarActionPerformed
     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UsoProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UsoProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UsoProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UsoProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UsoProducto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cantstop;
    private javax.swing.JButton cerrar;
    private javax.swing.JTextPane codigo;
    private javax.swing.JTextField fechacad;
    private javax.swing.JTextField fechaenv;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton limpiar;
    private javax.swing.JTextField numlote;
    private javax.swing.JTextField paisorg;
    private javax.swing.JTextField preciou;
    private javax.swing.JButton registrar2;
    private javax.swing.JButton registrar3;
    private javax.swing.JTable tabla;
    private javax.swing.JTextField temperatura;
    // End of variables declaration//GEN-END:variables
}
